package com.autohub.configuration;

import com.autohub.dto.FacebookPhotoPublishResponse;
import com.autohub.dto.FacebookProperties;
import com.autohub.exception.FacebookApiException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.retry.RecoveryCallback;
import org.springframework.retry.RetryCallback;
import org.springframework.retry.RetryContext;
import org.springframework.retry.support.RetryTemplate;
import org.springframework.stereotype.Component;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

/**
 * Talks to the Facebook Graph API "publish photo" endpoint - the mechanism
 * this module uses to turn one vehicle into one Facebook Page post (an
 * image post with a caption).
 * Never called directly from a controller - only from the async publish
 * worker (Phase 9/10), after a batch has already been committed.
 */
@Component
@Slf4j
public class FacebookGraphClient {

    private final WebClient facebookWebClient;
    private final FacebookProperties properties;
    private final RetryTemplate facebookRetryTemplate;
    private final ObjectMapper objectMapper;

    public FacebookGraphClient(@Qualifier("facebookWebClient") WebClient facebookWebClient,
                               FacebookProperties properties,
                               @Qualifier("facebookRetryTemplate") RetryTemplate facebookRetryTemplate,
                               ObjectMapper objectMapper) {
        this.facebookWebClient = facebookWebClient;
        this.properties = properties;
        this.facebookRetryTemplate = facebookRetryTemplate;
        this.objectMapper = objectMapper;
    }

    /**
     * Publishes a single photo post to the configured Facebook Page.
     *
     * @param imageUrl public HTTPS URL of the vehicle's primary image
     * @param caption  generated by CaptionGeneratorService
     */
    public FacebookPublishResult publishPhoto(String imageUrl, String caption) {

        RetryCallback<FacebookPublishResult, RuntimeException> retryCallback =
                (RetryContext context) -> {

                    log.info("Attempt [{}] - publishing photo to Facebook Page [{}]",
                            context.getRetryCount() + 1, properties.pageId());

                    MultiValueMap<String, String> form = new LinkedMultiValueMap<>();
                    form.add("url", imageUrl);
                    form.add("caption", caption);
                    form.add("access_token", properties.pageAccessToken());

                    try {
                        String responseJson = facebookWebClient.post()
                                .uri("/{version}/{pageId}/photos", properties.graphVersion(), properties.pageId())
                                .body(BodyInserters.fromFormData(form))
                                .retrieve()
                                .bodyToMono(String.class)
                                .block();

                        FacebookPhotoPublishResponse parsed =
                                objectMapper.readValue(responseJson, FacebookPhotoPublishResponse.class);

                        String postId = parsed.effectivePostId();
                        log.info("Facebook post published successfully. postId=[{}]", postId);

                        return new FacebookPublishResult(true, responseJson, postId,
                                buildPostUrl(postId), null, false);

                    } catch (WebClientResponseException.BadRequest
                             | WebClientResponseException.Unauthorized
                             | WebClientResponseException.Forbidden ex) {
                        // Invalid token, permission missing, invalid image URL, etc. -
                        // per the retry policy these must NOT be retried.
                        String body = ex.getResponseBodyAsString();
                        log.error("Permanent Facebook API failure (status={}): {}", ex.getStatusCode(), body);
                        throw new FacebookApiException(
                                "Facebook API rejected the request: " + ex.getStatusCode(), body, true, ex);

                    } catch (WebClientResponseException ex) {
                        // 5xx or 429 (rate limit) - transient, let facebookRetryTemplate retry.
                        log.warn("Transient Facebook API failure (status={}), will retry if attempts remain",
                                ex.getStatusCode());
                        throw ex;

                    } catch (JsonProcessingException ex) {
                        log.error("Failed to parse Facebook API response", ex);
                        throw new FacebookApiException("Failed to parse Facebook API response", null, true, ex);
                    }
                };

        RecoveryCallback<FacebookPublishResult> recoveryCallback =
                (RetryContext recoveryContext) -> {

                    Throwable lastException = recoveryContext.getLastThrowable();
                    String body = (lastException instanceof WebClientResponseException wcre)
                            ? wcre.getResponseBodyAsString() : null;

                    log.error("All retry attempts exhausted publishing to Facebook Page [{}]",
                            properties.pageId(), lastException);

                    return new FacebookPublishResult(false, body, null, null,
                            lastException != null ? lastException.getMessage() : "Unknown error", false);
                };

        return facebookRetryTemplate.execute(retryCallback, recoveryCallback);
    }

    private String buildPostUrl(String postId) {
        return "https://www.facebook.com/" + postId;
    }

    public record FacebookPublishResult(
            boolean success,
            String responsePayload,
            String facebookPostId,
            String facebookPostUrl,
            String errorMessage,
            boolean permanentFailure
    ) {}
}
