package com.autohub.configuration;

import com.autohub.dto.FacebookPhotoPublishResponse;
import com.autohub.dto.FacebookProperties;
import com.autohub.exception.FacebookApiException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.retry.RecoveryCallback;
import org.springframework.retry.RetryCallback;
import org.springframework.retry.RetryContext;
import org.springframework.retry.support.RetryTemplate;
import org.springframework.stereotype.Component;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

/**
 * Talks to the Facebook Graph API "publish photo" endpoint - the mechanism
 * this module uses to turn one vehicle into one Facebook Page post (an
 * image post with a caption).
 * Never called directly from a controller - only from the async publish
 * worker, after a batch has already been committed.
 */
@Component
@Slf4j
public class FacebookGraphClient {

    private final WebClient facebookWebClient;
    private final FacebookProperties properties;
    private final RetryTemplate facebookRetryTemplate;
    private final ObjectMapper objectMapper;

    public FacebookGraphClient(@Qualifier("facebookWebClient") WebClient facebookWebClient,
                               FacebookProperties properties,
                               @Qualifier("facebookRetryTemplate") RetryTemplate facebookRetryTemplate,
                               ObjectMapper objectMapper) {
        this.facebookWebClient = facebookWebClient;
        this.properties = properties;
        this.facebookRetryTemplate = facebookRetryTemplate;
        this.objectMapper = objectMapper;
    }

    /**
     * Publishes a single photo post to the configured Facebook Page.
     *
     * @param imageUrl public HTTPS URL of the vehicle's primary image
     * @param caption  generated by CaptionGeneratorService
     */
    public FacebookPublishResult publishPhoto(String imageUrl, String caption) {

        RetryCallback<FacebookPublishResult, RuntimeException> retryCallback =
                (RetryContext context) -> {

                    log.info("Attempt [{}] - publishing photo to Facebook Page [{}], imageUrl=[{}]",
                            context.getRetryCount() + 1, properties.pageId(), imageUrl);

                    MultiValueMap<String, String> form = new LinkedMultiValueMap<>();
                    form.add("url", imageUrl);
                    form.add("caption", caption);
                    form.add("access_token", properties.pageAccessToken());

                    try {
                        String responseJson = facebookWebClient.post()
                                .uri("/{version}/{pageId}/photos", properties.graphVersion(), properties.pageId())
                                .body(BodyInserters.fromFormData(form))
                                .retrieve()
                                .bodyToMono(String.class)
                                .block();

                        FacebookPhotoPublishResponse parsed =
                                objectMapper.readValue(responseJson, FacebookPhotoPublishResponse.class);

                        String postId = parsed.effectivePostId();
                        log.info("Facebook post published successfully. postId=[{}]", postId);

                        return new FacebookPublishResult(true, responseJson, postId,
                                buildPostUrl(postId), null, false);

                    } catch (WebClientResponseException.BadRequest
                             | WebClientResponseException.Unauthorized
                             | WebClientResponseException.Forbidden ex) {
                        // Invalid token, permission missing, invalid image URL, etc. -
                        // per the retry policy these must NOT be retried.
                        String body = ex.getResponseBodyAsString();
                        String reason = "Facebook API rejected the request (" + ex.getStatusCode() + "): "
                                + extractFacebookErrorMessage(body);
                        log.error("Permanent Facebook API failure. imageUrl=[{}] status=[{}] body=[{}]",
                                imageUrl, ex.getStatusCode(), body);
                        throw new FacebookApiException(reason, body, true, ex);

                    } catch (WebClientResponseException ex) {
                        // 5xx or 429 (rate limit) - transient, let facebookRetryTemplate retry.
                        log.warn("Transient Facebook API failure (status={}), will retry if attempts remain. body=[{}]",
                                ex.getStatusCode(), ex.getResponseBodyAsString());
                        throw ex;

                    } catch (JsonProcessingException ex) {
                        log.error("Failed to parse Facebook API response", ex);
                        throw new FacebookApiException("Failed to parse Facebook API response", null, true, ex);
                    }
                };

        RecoveryCallback<FacebookPublishResult> recoveryCallback =
                (RetryContext recoveryContext) -> {

                    Throwable lastException = recoveryContext.getLastThrowable();

                    String message;
                    String body = null;
                    if (lastException instanceof WebClientResponseException wcre) {
                        body = wcre.getResponseBodyAsString();
                        message = "Facebook API rejected the request (" + wcre.getStatusCode() + "): "
                                + extractFacebookErrorMessage(body);
                    } else {
                        message = lastException != null ? lastException.getMessage() : "Unknown error";
                    }

                    log.error("All retry attempts exhausted publishing to Facebook Page [{}]. lastError=[{}]",
                            properties.pageId(), message, lastException);

                    return new FacebookPublishResult(false, body, null, null, message, false);
                };

        return facebookRetryTemplate.execute(retryCallback, recoveryCallback);
    }

    /**
     * Facebook's error body looks like:
     * {"error":{"message":"...","type":"...","code":...,"error_subcode":...,
     * "fbtrace_id":"..."}}. Pulls out the human-readable "message" (and code,
     * if present) so it's actually useful in SocialPostBatchItem.errorMessage
     * instead of just a bare HTTP status.
     */
    private String extractFacebookErrorMessage(String responseBody) {
        if (responseBody == null || responseBody.isBlank()) {
            return "No response body from Facebook";
        }
        try {
            JsonNode root = objectMapper.readTree(responseBody);
            JsonNode error = root.path("error");
            if (error.isMissingNode()) {
                return responseBody;
            }
            String message = error.path("message").asText("Unknown error");
            int code = error.path("code").asInt(-1);
            int subcode = error.path("error_subcode").asInt(-1);
            StringBuilder sb = new StringBuilder(message);
            if (code != -1) {
                sb.append(" (code=").append(code);
                if (subcode != -1) {
                    sb.append(", subcode=").append(subcode);
                }
                sb.append(")");
            }
            return sb.toString();
        } catch (JsonProcessingException ex) {
            // Body wasn't JSON - just return it raw rather than losing it.
            return responseBody;
        }
    }

    private String buildPostUrl(String postId) {
        return "https://www.facebook.com/" + postId;
    }

    public record FacebookPublishResult(
            boolean success,
            String responsePayload,
            String facebookPostId,
            String facebookPostUrl,
            String errorMessage,
            boolean permanentFailure
    ) {}
}
