package com.autohub.configuration;

import com.autohub.dto.InstagramProperties;
import com.autohub.exception.InstagramApiException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.retry.RecoveryCallback;
import org.springframework.retry.RetryCallback;
import org.springframework.retry.RetryContext;
import org.springframework.retry.support.RetryTemplate;
import org.springframework.stereotype.Component;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

/**
 * Talks to the Instagram Graph API using the two-step container publishing
 * flow:
 * <ol>
 *   <li>POST /{ig-user-id}/media  → creates a media container (returns creation_id)</li>
 *   <li>POST /{ig-user-id}/media_publish → publishes the container (returns post id)</li>
 * </ol>
 * Never called directly from a controller - only from the async publish
 * worker, after a batch has already been committed.
 */
@Component
@Slf4j
public class InstagramGraphClient {

    private final WebClient instagramWebClient;
    private final InstagramProperties properties;
    private final RetryTemplate instagramRetryTemplate;
    private final ObjectMapper objectMapper;

    public InstagramGraphClient(@Qualifier("instagramWebClient") WebClient instagramWebClient,
                                InstagramProperties properties,
                                @Qualifier("instagramRetryTemplate") RetryTemplate instagramRetryTemplate,
                                ObjectMapper objectMapper) {
        this.instagramWebClient = instagramWebClient;
        this.properties = properties;
        this.instagramRetryTemplate = instagramRetryTemplate;
        this.objectMapper = objectMapper;
    }

    /**
     * Publishes a single photo post to the configured Instagram Business Account
     * using the two-step container approach.
     *
     * @param imageUrl public HTTPS URL of the vehicle's primary image
     * @param caption  generated by InstagramCaptionGeneratorService
     */
    public InstagramPublishResult publishPhoto(String imageUrl, String caption) {

        RetryCallback<InstagramPublishResult, RuntimeException> retryCallback =
                (RetryContext context) -> {

                    log.info("Attempt [{}] - publishing photo to Instagram Account [{}], imageUrl=[{}]",
                            context.getRetryCount() + 1, properties.accountId(), imageUrl);

                    try {
                        // ====== Step 1: Create media container ======
                        String creationId = createMediaContainer(imageUrl, caption);
                        log.info("Instagram media container created. creationId=[{}]", creationId);

                        // ====== Step 2: Publish the media container ======
                        String postId = publishMediaContainer(creationId);
                        log.info("Instagram post published successfully. postId=[{}]", postId);

                        String postUrl = buildPostUrl(postId);

                        return new InstagramPublishResult(true, postId, creationId, postUrl, null, false);

                    } catch (WebClientResponseException.BadRequest
                             | WebClientResponseException.Unauthorized
                             | WebClientResponseException.Forbidden ex) {
                        // Invalid token, permission missing, invalid image URL, etc. -
                        // per the retry policy these must NOT be retried.
                        String body = ex.getResponseBodyAsString();
                        String reason = "Instagram API rejected the request (" + ex.getStatusCode() + "): "
                                + extractInstagramErrorMessage(body);
                        log.error("Permanent Instagram API failure. imageUrl=[{}] status=[{}] body=[{}]",
                                imageUrl, ex.getStatusCode(), body);
                        throw new InstagramApiException(reason, body, true, ex);

                    } catch (WebClientResponseException ex) {
                        // 5xx or 429 (rate limit) - transient, let instagramRetryTemplate retry.
                        log.warn("Transient Instagram API failure (status={}), will retry if attempts remain. body=[{}]",
                                ex.getStatusCode(), ex.getResponseBodyAsString());
                        throw ex;

                    } catch (JsonProcessingException ex) {
                        log.error("Failed to parse Instagram API response", ex);
                        throw new InstagramApiException("Failed to parse Instagram API response", null, true, ex);
                    }
                };

        RecoveryCallback<InstagramPublishResult> recoveryCallback =
                (RetryContext recoveryContext) -> {

                    Throwable lastException = recoveryContext.getLastThrowable();

                    String message;
                    String body = null;
                    if (lastException instanceof WebClientResponseException wcre) {
                        body = wcre.getResponseBodyAsString();
                        message = "Instagram API rejected the request (" + wcre.getStatusCode() + "): "
                                + extractInstagramErrorMessage(body);
                    } else {
                        message = lastException != null ? lastException.getMessage() : "Unknown error";
                    }

                    log.error("All retry attempts exhausted publishing to Instagram Account [{}]. lastError=[{}]",
                            properties.accountId(), message, lastException);

                    return new InstagramPublishResult(false, null, null, null, message, false);
                };

        return instagramRetryTemplate.execute(retryCallback, recoveryCallback);
    }

    /**
     * Step 1: Create a media container on Instagram.
     * POST /{ig-user-id}/media?image_url=...&caption=...&access_token=...
     */
    private String createMediaContainer(String imageUrl, String caption) throws JsonProcessingException {

        MultiValueMap<String, String> form = new LinkedMultiValueMap<>();
        form.add("image_url", imageUrl);
        form.add("caption", caption);
        form.add("access_token", properties.accessToken());

        String responseJson = instagramWebClient.post()
                .uri("/{version}/{accountId}/media", properties.graphVersion(), properties.accountId())
                .body(BodyInserters.fromFormData(form))
                .retrieve()
                .bodyToMono(String.class)
                .block();

        JsonNode root = objectMapper.readTree(responseJson);
        String creationId = root.path("id").asText(null);

        if (creationId == null || creationId.isBlank()) {
            throw new InstagramApiException(
                    "Instagram media container creation returned no id. Response: " + responseJson,
                    responseJson, true);
        }

        return creationId;
    }

    /**
     * Step 2: Publish the media container.
     * POST /{ig-user-id}/media_publish?creation_id=...&access_token=...
     */
    private String publishMediaContainer(String creationId) throws JsonProcessingException {

        MultiValueMap<String, String> form = new LinkedMultiValueMap<>();
        form.add("creation_id", creationId);
        form.add("access_token", properties.accessToken());

        String responseJson = instagramWebClient.post()
                .uri("/{version}/{accountId}/media_publish", properties.graphVersion(), properties.accountId())
                .body(BodyInserters.fromFormData(form))
                .retrieve()
                .bodyToMono(String.class)
                .block();

        JsonNode root = objectMapper.readTree(responseJson);
        String postId = root.path("id").asText(null);

        if (postId == null || postId.isBlank()) {
            throw new InstagramApiException(
                    "Instagram media_publish returned no id. Response: " + responseJson,
                    responseJson, true);
        }

        return postId;
    }

    /**
     * Instagram's error body follows the same format as Facebook:
     * {"error":{"message":"...","type":"...","code":...,"error_subcode":...,
     * "fbtrace_id":"..."}}. Pulls out the human-readable "message" (and code,
     * if present).
     */
    private String extractInstagramErrorMessage(String responseBody) {
        if (responseBody == null || responseBody.isBlank()) {
            return "No response body from Instagram";
        }
        try {
            JsonNode root = objectMapper.readTree(responseBody);
            JsonNode error = root.path("error");
            if (error.isMissingNode()) {
                return responseBody;
            }
            String message = error.path("message").asText("Unknown error");
            int code = error.path("code").asInt(-1);
            int subcode = error.path("error_subcode").asInt(-1);
            StringBuilder sb = new StringBuilder(message);
            if (code != -1) {
                sb.append(" (code=").append(code);
                if (subcode != -1) {
                    sb.append(", subcode=").append(subcode);
                }
                sb.append(")");
            }
            return sb.toString();
        } catch (JsonProcessingException ex) {
            return responseBody;
        }
    }

    /**
     * Builds the public Instagram post URL from the post ID.
     * The Instagram Graph API returns numeric post IDs, but the web URL
     * requires the permalink which can be fetched via the API. For simplicity,
     * we store a link to the media via the Graph API's permalink field, or
     * fall back to the Instagram profile link.
     */
    private String buildPostUrl(String postId) {
        // The permalink for an Instagram post can be fetched with:
        // GET /{post-id}?fields=permalink&access_token=...
        // For robustness, we do a best-effort fetch here. If it fails, we
        // return a fallback URL.
        try {
            String responseJson = instagramWebClient.get()
                    .uri("/{version}/{postId}?fields=permalink&access_token={token}",
                            properties.graphVersion(), postId, properties.accessToken())
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            JsonNode root = objectMapper.readTree(responseJson);
            String permalink = root.path("permalink").asText(null);
            if (permalink != null && !permalink.isBlank()) {
                return permalink;
            }
        } catch (Exception ex) {
            log.warn("Could not fetch Instagram permalink for postId=[{}]: {}", postId, ex.getMessage());
        }
        // Fallback: direct link via Instagram media ID
        return "https://www.instagram.com/p/" + postId + "/";
    }

    /**
     * Posts a comment on an already-published Instagram media post.
     * Uses: POST /{media-id}/comments?message=...&access_token=...
     *
     * This is best-effort — if the comment fails, it logs a warning but
     * does NOT affect the overall publish status of the post.
     *
     * @param mediaPostId the Instagram post ID returned by media_publish
     * @param commentText the comment body (vehicle details + link)
     */
    public void postComment(String mediaPostId, String commentText) {
        try {
            MultiValueMap<String, String> form = new LinkedMultiValueMap<>();
            form.add("message", commentText);
            form.add("access_token", properties.accessToken());

            String responseJson = instagramWebClient.post()
                    .uri("/{version}/{mediaId}/comments", properties.graphVersion(), mediaPostId)
                    .body(BodyInserters.fromFormData(form))
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            JsonNode root = objectMapper.readTree(responseJson);
            String commentId = root.path("id").asText(null);

            if (commentId != null && !commentId.isBlank()) {
                log.info("Instagram comment posted successfully on post [{}]. commentId=[{}]",
                        mediaPostId, commentId);
            } else {
                log.warn("Instagram comment API returned no id for post [{}]. Response: {}",
                        mediaPostId, responseJson);
            }

        } catch (Exception ex) {
            log.warn("Failed to post comment on Instagram post [{}]: {}. " +
                     "The post itself was published successfully — comment is non-critical.",
                    mediaPostId, ex.getMessage());
        }
    }

    public record InstagramPublishResult(
            boolean success,
            String instagramPostId,
            String instagramMediaId,
            String instagramPostUrl,
            String errorMessage,
            boolean permanentFailure
    ) {}
}
